name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      NODE_ENV: "test"
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn test
      
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi"
