name: publish

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      NODE_ENV: "test"
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      
    steps:
      - uses: actions/checkout@v2
      
      - run: yarn && yarn test
      
  deploy:
    needs: test
    # Only runs on if it's a push event on main
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    environment: deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo whoami      
            
