name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      NODE_ENV: "development"
    steps:
      - uses: actions/checkout@v2
      - run: echo "$DISCORD_TOKEN"
      - run: yarn && yarn start
